# Generated by Django 3.2.6 on 2022-03-18 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apolloapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='userid',
        ),
        migrations.AddField(
            model_name='tickets',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apolloapp.user'),
            preserve_default=False,
        ),
    ]
